version: '3.8'

services:
  client:
    build: ./client
    image: client_img
    container_name: client_cont
    ports:
      - 3000:3000
    volumes:
      - ./client:/client  # Mount local client directory to container
      - /client/node_modules  # Ensure node_modules aren't overwritten
    depends_on:
      - server

  server:
    build: ./server
    image: server_img
    container_name: server_cont
    ports:
      - 8080:8080
    volumes:
      - ./server:/server
      - /server/node_modules  # Ensure node_modules aren't overwritten
    env_file:
      - ./server/.env
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:latest
    container_name: db_cont
    env_file:
      - ./server/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 7